# Generated by Django 3.2.13 on 2022-10-26 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='StatusSenha',
            fields=[
                ('id_status_senha', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id_tipo', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Senha',
            fields=[
                ('id_senha', models.AutoField(primary_key=True, serialize=False)),
                ('senha', models.IntegerField()),
                ('fk_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='painel_senhas.categoria')),
                ('fk_status_senha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='painel_senhas.statussenha')),
                ('fk_tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='painel_senhas.tipo')),
            ],
        ),
    ]
